[package]
name = "day_09"
version = "0.1.0"
authors = ["Sebastian Reinhard <sebastian@sebbert.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"
intcode = { path = "../intcode" }
